import pandas as pd
import hashlib

# transform data to fit date dimension
def getDates(df):
    print("Transforming Datetime Data")

    df = df[["date.#text"]].copy()
    #convert timezones
    df["date"] = pd.to_datetime(df["date.#text"]).dt.tz_localize('gmt')
    df["date"] = pd.to_datetime(df["date"]).dt.tz_convert('America/New_York') # change to local timezone
    df["date"] = pd.to_datetime(df["date"]).dt.date
    
    df = df.drop(columns=["date.#text"])
    df = df.sort_values(by="date")
    df = df.drop_duplicates(ignore_index=True)

    # primary key generated by concatenation of date
    df["date_key"] = df["date"].astype(str).str.replace("-", "").astype(int)
    df["year"] = pd.to_datetime(df["date"]).dt.year
    df["month"] = pd.to_datetime(df["date"]).dt.month
    df["day"] = pd.to_datetime(df["date"]).dt.day
    df["day_of_week"] = pd.to_datetime(df["date"]).dt.dayofweek

    df = df[["date_key", "date", "day", "month", "year", "day_of_week"]]

    return df


# transform data to fit time of day dimension
def getTimeOfDay(df):
    print("Transforming Time Data")

    df = df[["date.#text"]].copy()
    #convert timezones
    df["date.#text"] = pd.to_datetime(df["date.#text"]).dt.tz_localize('gmt')
    df["date.#text"] = pd.to_datetime(df["date.#text"]).dt.tz_convert('America/New_York') # change to local timezone
    df["time"] = pd.to_datetime(df["date.#text"]).dt.time

    # primary key generated by concatenation of time
    df["time_of_day_key"] = df["time"].astype(str).str.replace(":", "").astype(int)
    df["hour"] = pd.to_datetime(df["date.#text"]).dt.hour
    df = df.drop(columns=["date.#text"])
    df = df.sort_values(by="time")
    df = df.drop_duplicates(ignore_index=True)

    df = df[["time_of_day_key", "time", "hour"]]
    
    return df


# transform data to fit track dimension
def getTracks(df):
    print("Transforming Track Data")

    df = df[["name", "album.#text"]].copy()
    df = df.drop_duplicates(keep="first", ignore_index=True)
    df = df.rename(columns={"name": "track_name", "album.#text": "album_name"})

    # md5 hash of track name and album name for track_key https://docs.getdbt.com/blog/sql-surrogate-keys
    df["temp"] = df["track_name"] + df["album_name"]
    df["track_key"] = [hashlib.md5(key.encode('utf-8')).hexdigest() for key in df["temp"]]
    df = df.drop(columns=["temp"])

    df = df[["track_key", "track_name", "album_name"]]

    return df


# transform data to fit artist dimension
def getArtists(df):
    print("Transforming Artist Data")

    # artist name stored as commas separated string in artist.#text
    # must split into individual artists
    df = df[["artist.#text"]].copy()
    df = df["artist.#text"].str.split(", ")
    df = df.explode("artist.#text").to_frame()
    df = df.drop_duplicates(ignore_index=True)
    df = df.rename(columns={"artist.#text": "artist_name"})

    # key generated through md5 hash of artist name
    df["artist_key"] = [hashlib.md5(key.encode('utf-8')).hexdigest() for key in df["artist_name"]]

    df = df[["artist_key", "artist_name"]]

    return df


# transform data to fit artist group dimension
# artist group can be a single artist or a group of artists
def getArtistGroups(df):
    print("Transforming Artist Group Data")

    df = df[["artist.#text"]].copy()
    df = df.drop_duplicates(ignore_index=True)
    df = df.rename(columns={"artist.#text": "artist_group_name"})

    # key generated through md5 hash of artist name
    df["artist_group_key"] = [hashlib.md5(key.encode('utf-8')).hexdigest() for key in df["artist_group_name"]]

    df = df[["artist_group_key", "artist_group_name"]]

    return df


# connects artist and artist group dimension by joining and flattening the keys from each dimension
def getArtistGroupBridge(artist_dim, artist_group_dim):
    print("Transforming Artist Group Bridge Data")

    df = artist_group_dim[["artist_group_key", "artist_group_name"]].copy()
    df["artist_group_name"] = df["artist_group_name"].str.split(", ")
    df = df.explode("artist_group_name")
    df = df.merge(artist_dim, how="left", left_on="artist_group_name", right_on="artist_name")
    df = df.drop(columns=["artist_group_name", "artist_name"])
    df = df.drop_duplicates(ignore_index=True)

    df = df[["artist_group_key", "artist_key"]]

    return df


# generate factless fact table using key generation techniques from dimensions
# no surrogate key necessary for fact table
def getListeningFact(tracks):
    print("Transforming Listening Fact Data")

    df = tracks[["date.#text", "name", "album.#text", "artist.#text"]].copy()
    df["date.#text"] = pd.to_datetime(df["date.#text"]).dt.tz_localize('gmt')
    df["date.#text"] = pd.to_datetime(df["date.#text"]).dt.tz_convert('America/New_York') # change to local timezone
    df["date_key"] = pd.to_datetime(df["date.#text"]).dt.date
    df["date_key"] = df["date_key"].astype(str).str.replace("-", "").astype(int)
    df["time_of_day_key"] = pd.to_datetime(df["date.#text"]).dt.time
    df["time_of_day_key"] = df["time_of_day_key"].astype(str).str.replace(":", "").astype(int)
    df["track_key"] = df["name"] + df["album.#text"]
    df["track_key"] = [hashlib.md5(key.encode('utf-8')).hexdigest() for key in df["track_key"]]
    df["artist_group_key"] = [hashlib.md5(key.encode('utf-8')).hexdigest() for key in df["artist.#text"]]
    df = df.drop(columns=["date.#text", "name", "album.#text", "artist.#text"]) 

    df = df[["date_key", "time_of_day_key", "track_key", "artist_group_key"]]

    return df